### ISSUE TITLE
Creating README.MD for beniyiyim.com

### ISSUE THREAD

**Issue by itsmokur** [acikkaynak/ben-iyiyim-frontend#4]
We have created readme.md for beniyiyim.com, please proceed it to production.

PR ID: a45f4f31d82bbab9f86c0047a6bc1fae5103c129

https://github.com/acikkaynak/ben-iyiyim-frontend/pull/5

**Comment by cengizcmataraci** [comment]
Mergelenmiş burayı kapatabiliriz @fdemir

**Comment by fdemir** [comment]
ok
